SmartVouchersService:
  Db:
    LogsConnString:
      settings-key: SmartVouchersService-LogsConnString
      types:
        - AzureTableStorage
    SqlDbConnString:
      settings-key: SmartVouchersService-SqlDbConnString
    CampaignsImageConnString:
      settings-key: SmartVouchersService-CampaignsImageConnString
      types:
        - AzureTableStorage
  Rabbit:
    Publishers:
      ConnectionString:
        settings-key: WalletManagementRabbitMQ
        types:
          - RabbitMq
    Subscribers:
      ConnectionString:
        settings-key: WalletManagementRabbitMQ
        types:
          - RabbitMq
  Redis:
    ConnectionString:
      settings-key: SmartVouchersService-Redis-ConnectionString
  VoucherLockTimeOut:
    settings-key: SmartVouchersService-VoucherLockTimeOut
SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl
PaymentManagementServiceClient:
    ServiceUrl:
        settings-key: PaymentManagementServiceUrl
